version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: twinx_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: postgres

  twinx:
    container_name: twinx_main
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL}

volumes:
  pgdata:
